[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
test = "test"
evm_version = "paris"
extra_output = ["metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

out = 'build-forge'
libs = ['lib', 'node_modules']
remappings = [
    'forge-std/=lib/forge-std/src/',
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/",
    "price-oracle/=src/",
]

[fmt]
line_length = 100
multiline_func_header = "params_first"
# wrap_comments = true


[profile.production]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
