[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.16"

[features]
resolution = true

[test.validator]
# AjX3A4Nv2rzUuATEUWLP4rrBaBropyUnHxEvFDj1dKbx - this feature disables memory gaps.
# We disable it because we want to test execution like in devnet or mainnet.
# See https://github.com/anza-xyz/agave/blob/v2.2.7/feature-set/src/lib.rs
deactivate_feature = ["AjX3A4Nv2rzUuATEUWLP4rrBaBropyUnHxEvFDj1dKbx"]

[[test.genesis]]
name = "price-oracle"
address = "CefQJaxQTV28gCf4MMd1PgDHgCcRmuEHZgXZwjJReUY3"
program = "../../price-oracle/solana/target/sbf-solana-solana/release/solana_price_oracle.so"
upgradeable = true

[[test.genesis]]
name = "cctpr"
address = "CctpRNMoG3Xs4MF4i9hAfMQFBZ4zJDvhUA4k2EJd8XEW"
program = "target/sbf-solana-solana/release/cctpr.so"
upgradeable = true

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./target/deploy/cctpr-keypair.json" #"~/.config/solana/id.json"

[scripts]
setup-test = "cd ../../price-oracle/solana; cargo build-sbf -- -p solana-price-oracle"
test = "yarn run mocha -t 1000000 tests/cctpr.ts"

[test]
upgradeable = true
