[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.16"

[features]
resolution = true

[provider]
cluster = "localnet"
wallet = "./target/deploy/cctpr-keypair.json" #"~/.config/solana/id.json"
