name: CI Backend
run-name: "Running for Backend ${{ inputs.branch }} ${{ inputs.app_version }}"
on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Application version'
        required: true
        type: string
      branch:
        description: 'Branch or SHA to use as source'
        required: true
        type: string

jobs:
  build:
    name: Build
    uses: stable-io/gha-workflows/.github/workflows/ci_docker.yaml@v1.1.0
    with:
      app_name: backend
      app_version: ${{ inputs.app_version }}
      ecr_repository: stable/back-end
      git_ref: ${{ inputs.branch }}
      path_dockerfile: apps/back-end/Dockerfile
      path_workspace: .
      push_tag_without_sha: true 
