name: Frontend Build and Deploy to AWS
# Use this workflow trigger if you want to run this
# after merging Pull requests to main
# on:
#   pull_request:
#     types:
#       - closed
#   branches:
#       - 'main'

# Triggers this workflow manually
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  S3_BUCKET: prod-stable-website
  AWS_CF_DIST_ID: E2M0T5LE7CSRQM
  BUILT_PATH: apps/front-end/dist
  AWS_IAM_ROLE: arn:aws:iam::815253839295:role/stable-explorer-gha
  AWS_REGION: us-east-2

jobs:
  build-and-deploy:
    # Also uncomment this line for triggering the job only after
    # merging Pull Requests to main
    # if: github.event.pull_request.merged == true
    name: Build and Deploy
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Set up Yarn
        run: |
          corepack enable
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set up environment variables
        run: cp ./apps/front-end/.env.local.example ./apps/front-end/.env.local

      - name: Build
        run: yarn build
  
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume:  ${{ env.AWS_IAM_ROLE }}
          role-session-name: github-stable-explorer
          aws-region: ${{ env.AWS_REGION }}

# --delete flag also removes on destination the files that are not present
# in the source
      - name: Upload Static files to S3
        run: |
          aws s3 sync ${BUILT_PATH} \
                      s3://${S3_BUCKET} \
                      --delete 

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${AWS_CF_DIST_ID} \
            --paths "/*"